# Generated by Django 5.0.2 on 2024-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TimeField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=30)),
            ],
        ),
    ]
